### ISSUE TITLE
Subscription payments with Stripe

### ISSUE THREAD

**Issue by tlmader** [cerberus-org/cerberus-app#227]
## Description

Add subscription payments with Stripe.
* Video: [Subscription Payments with Stripe, Angular, and Firebase](https://www.youtube.com/watch?v=QYvANSdlKjQ)

## Tasks

- [ ] Add Stripe customer on organization creation.
- [ ] Add payment portal for subscription.
- [ ] Display active subscription info.
