### ISSUE TITLE
Privacy/TOS for check-in page

### ISSUE THREAD

**Issue by tlmader** [cerberus-org/cerberus-app#264]
## Description

If this is a feature request, include a description here and apply the green _feature_ label.

## Tasks

- [x] Add checkbox for TOS agreement to new volunteer form.
- [x] Add modal for viewing Privacy Policy/TOS
- [x] A via [fab button](https://material.angular.io/components/button/examples) in bottom-right of page.
