### ISSUE TITLE
Add ability for users to set dates on visits

### ISSUE THREAD

**Issue by tlmader** [cerberus-org/cerberus-app#265]
## Description

Users should be able to manually set start and end dates of visits. This will handle cases where volunteers forget to check in or out.

## Tasks

- [x] Add a "Visits" page with a data table to Settings.
- [x] Add a datepicker setting to `ColumnOptions` and update the `data-table` component.
- [ ] Add `lastUpdatedBy` property to visit to track who updated the visit.
- [ ] Display the user who last updated a visit on the visits data table.

**Comment by harurang** [comment]
Audit table not included.
