### ISSUE TITLE
Shared NgModule

### ISSUE THREAD

**Issue by tlmader** [cerberus-org/cerberus-app#281]
## Description

Create an NgModule for all shared components and services, and use this in a feature module and the app module.

## Tasks

- [x] Create shared NgModule.
- [x] Create feature module for settings.
- [x] Import shared NgModule.
