### ISSUE TITLE
Remove Firebase Authentication UID from User primary key

### ISSUE THREAD

**Issue by tlmader** [cerberus-org/cerberus-app#287]
## Description

The Firebase Authentication UID should be a property of the User model, rather than used as a primary key. This would allow us to create multiple User objects per Firebase Authentication user. The updated model should be called _Member_ to better describe its purpose.

## Tasks

- [ ] Create the Member model based on our User model, but with its own generated primary key and the Firebase Authentication UID as a property.
- [ ] Update usages of the User model.
- [ ] Update User creation workflows.

**Comment by tlmader** [comment]
Resolved by #289
