### ISSUE TITLE
Teams module and sign up forms redesign

### ISSUE THREAD

**Issue by tlmader** [cerberus-org/cerberus-app#310]
## Description

Create a page for creating and joining teams. The page should display a list of teams for the current user and provide actions for navigating to check-in and team settings. Additionally, the existing sign up forms will need to be redesigned.

## Tasks

- [x] Create TeamsModule with _Teams_ page.
- [x] Fetch teams for current user and display on page.
- [ ] Add dialogs for create and join organization.
- [ ] Add updated dialog for sign up to home page.
